export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LayoutProfile({ children }) {
  return <>
  <h2>Estamos en el menu de layoutProfile</h2>
  {children}
  </>;
}
